name: publish

on:
  workflow_dispatch:
  push:
    tags:
      - '*'
     
      
env:
  DOTNET_VERSION: '6.0.x' # The .NET SDK version to use
  PublishFilePath: C:\PublishFiles
  
jobs:
  publish:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Install dependencies
      run: dotnet restore
     
    - name: Get tag
      if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') }}
      id: tag
      uses: dawidd6/action-get-tag@v1
      
    - name: Build
      run: |
        dotnet build --configuration Release --no-restore
        dotnet publish -c Release -r win-x86 --sc false /p:PublishSingleFile=True /p:PublishProfile=${{ env.PublishFilePath }}
        
    - name: Test
      run: |
        dotnet test --no-restore --verbosity normal
    - name: Changelog
      uses: glennawatson/ChangeLog@v1
      id: changelog

    - name: Create a new GitHub release
      uses: ncipollo/release-action@v1
      if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') }}
      with:
        token: ${{ secrets.GH_TOKEN }}
        name: ${{ steps.tag.outputs.tag }}
        prerelease: false
        draft: true
        artifacts: ${{ env.PublishFilePath }}\*.exe
        body: |
          ## 版本亮点
          * 此版本由 GitHub Action 自动化部署发布，更新日志会在一段时间后手动更新。
          ${{ steps.changelog.outputs.commitLog }}
