name: Release

on:
  push:
    tags:
      - '*'

env:
  DOTNET_VERSION: '6.0.x' # The .NET SDK version to use

jobs:
  release:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Install dependencies
      run: dotnet restore Soda_Craft_Launcher.sln

    - name: Init Token
      run: |
        $token_xaml = "${{ secrets.TOKEN_XAML }}"
        $token_path = Join-Path -Path D:\a\SodaCL\SodaCL\Dictronaries\ -ChildPath Token.xaml
        [IO.File]::WriteAllText("$token_path", $token_xaml)

    - name: Build
      run: |
        dotnet build Soda_Craft_Launcher.sln --configuration Release --no-restore
        dotnet publish Soda_Craft_Launcher.sln -c Release -r win-x86 --sc false /p:PublishSingleFile=True

    - name: Test
      run: |
        dotnet test Soda_Craft_Launcher.sln --no-restore --verbosity normal

    - name: Changelog
      uses: glennawatson/ChangeLog@v1
      id: changelog

    - name: Release
      uses: softprops/action-gh-release@v0.1.13
      if: startsWith(github.ref, 'refs/tags/')
      with:
          fail_on_unmatched_files: true
          body: |
            ## 版本亮点
            * 此版本由 GitHub Action 自动化部署发布，更新日志会在一段时间后手动更新,长时间不更新那就是咕咕咕啦~

            ${{ steps.changelog.outputs.commitLog }}
          files: |
            D:\a\SodaCL\SodaCL\bin\Release\net6.0-windows\win-x86\publish\SodaCL.exe